### ISSUE TITLE
Add support for simple search query (scan/scroll)

### ISSUE THREAD

**Issue by darkwarriors** [WedjaaOpen/ElasticParser#1]
Hi,

i leave this remainder, because i dont find a way to use ElasticSearch simple search query for retrive raw documents  and put them in table or aggregate it with jasper. As i add in the title, support for scan and scroll query type ( http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/scan-scroll.html ) would allow ppl to fetch GB of dates without consuming too much resources.

i leave this comment also as a my remainder, i will try to help to create the correct parser for simple search query.

Regards.

**Comment by Wedjaa** [comment]
Hi,

 did you try with 'hit' mode? You should be able to run queries and get raw hits. Can you give me an example query that doesn't work?

**Comment by darkwarriors** [comment]
yes hits query type is working good, but there are 2 problems:
1- with large amount of data there could be a huge utilization of resources and query could timeout, this can be solved with the new scan and scroll method.
2- we are not able to add aggregation dataadpter and hits dataadpter in same report / subreport, are we missing something or 2 different dataadpter cant be used in same report ?

Thanks for all you support1

Regards

**Comment by Wedjaa** [comment]
Hi!

  You can use different connections for the sub-reports, rather than using the main one, it will allow you then to have sub-reports with different results type from the master report. 

  I'll keep the issue open, and look into implementing the use of scan/scroll for large datasets. I have to admit I was naive in implementing it as it is - discarding scan/scroll - because I couldn't think of a use case where you would want a report with GB of data. I think I stand corrected! :)

**Comment by darkwarriors** [comment]
thanks alot for the clarification, but iam stuck on using another dataadapter on subreport i have search alot in google and jasper community but seems that there arent a general solution on that, have you some experience on this implementantion ? i have try to add manually a connection expression inside the xml of subreport but without success, have you some suggestions ?

yes you are right i agree with you that select gb of data should be very rare, but we have experience many use case on this because many times happened that we would like to produce a report that try to include data of past 4 mounth, even if it will end up in 50 pages report.. scan and scroll method will remove from cache every buckets that we search so the cluster can use less memory for a single search, this can be added as enchantment for the future!

Thanks alot and best regards.

**Comment by Wedjaa** [comment]
Hi Darkwarriors, I just committed a branch that uses ES scrolls to page hits results; it also fixes some issues with the way Aggregations are unrolled. Will soon make it the master branch.

**Comment by darkwarriors** [comment]
thanks alot! i'll try it asap.

iam still looking around for a solution about what i explain above "2- we are not able to add aggregation dataadpter and hits dataadpter in same report / subreport, are we missing something or 2 different dataadpter cant be used in same report ?" , have you got time to see it or test  it ? 

i try to manually add in xml a new dataadapter to a specific subreport but seems that i didnt find any correct sintax for it, i have tried all solution that we found in the community forum without success.

best regards
