### ISSUE TITLE
Add compatibility with Elasticsearch Shield plugin

### ISSUE THREAD

**Issue by ThomasFlanaghan** [WedjaaOpen/ElasticParser#12]
There is no current support to authenticate the shield plugin for elastic. This means you have to disable your security to run any reports and leaves the Elastic clusters open to the world. There is a username and password field that, after looking through the code, isn't used but it says on the official blog instructions that it does. 

Thanks.

**Comment by ghost** [comment]
Hi,

I face to the same issue.

 Shield authentication is not available. You just have to add the 'Shield.user' entry in the settings when building the client.

Best regards

**Comment by ThomasFlanaghan** [comment]
Hi David,

Could you give any more info?
I have tried lots of different ways to try and add shield authentication to the plugin to no avail.
Java is not my strongest. 

Thanks,
Thomas

**Comment by ghost** [comment]
Hi Thomas,

You will find more details on the [ES documentation](https://www.elastic.co/guide/en/shield/shield-1.3/_using_elasticsearch_java_clients_with_shield.html).

Best regards,
david

**Comment by ghost** [comment]
Hi Thomas,

To use Shield, the associated jar must be added into the OSGI bundle. See the associated issue.

Then, you can modify the code from the ESSearch class of the ESParser:

```
@SuppressWarnings("unchecked")
    public void connect() {
        if (esClient != null && keepClient) {
            LOGGER.debug(
                    "We are already connected with a passed on client - not creating a new one");
            return;
        }

        LOGGER.debug("Creating new client to connect to: " + hostname);

        // Prepare a client for the ES Server
        final Builder settingsBuilder = Settings.settingsBuilder();
        settingsBuilder.put("cluster.name", cluster).put("client.transport.sniff", true);
        final org.elasticsearch.client.transport.TransportClient.Builder transportBuilder =
                TransportClient.builder();

        if (!(username == null || username.isEmpty() || password == null || password.isEmpty())) {
            final String pluginClassName = "org.elasticsearch.shield.ShieldPlugin";

            try {
                transportBuilder.addPlugin((Class<? extends Plugin>)Class.forName(pluginClassName));
                settingsBuilder.put("shield.user", username + ':' + password);
            }
            catch (final ClassNotFoundException e) {
                LOGGER.warn("Plugin not found: " + pluginClassName, e);
            }
        }

        final InetSocketTransportAddress transportAddress =
                new InetSocketTransportAddress(new InetSocketAddress(hostname, port));
        final TransportClient transportClient =
                transportBuilder.settings(settingsBuilder.build()).build();
        transportClient.addTransportAddress(transportAddress);
        esClient = transportClient;
    }
```

Thanks,

I did not have tested the code yet. 
I use a similar code and it works fine. 
Please, let me know.

Best regards,
david

**Comment by ThomasFlanaghan** [comment]
Hi David,

Thank you for your help. I will try this and let you know how it goes.

Thanks,
Tom

**Comment by Wedjaa** [comment]
Added support for Shield. Propagating the version change upstream to the Jasper Studio and Jasper Server modules.

**Comment by Wedjaa** [comment]
Plugin updated - it can now be installed from the distribution site. Implemented the Shield username/password authentication.
